./plotCostFunction.sh "001_lan_diurnalFirewallCapture"
./plotCostFunction.sh "001_wireshark-wiki_tftp_wrq"
./plotCostFunction.sh "001_wireshark-wiki_eigrp-for-ipv6-auth"
./plotCostFunction.sh "001_wireshark-wiki_dhcp-nanosecond"
./plotCostFunction.sh "001_stp"
./plotCostFunction.sh "001_RIPv2_subnet_down"
./plotCostFunction.sh "001_ospf_over_gre_tunnel"
./plotCostFunction.sh "001_bgp"
./plotCostFunction.sh "001_equinix-1s"
./plotCostFunction.sh "001_tcpreplay_bigFlows"
./plotCostFunction.sh "001_tcpreplay_bigFlows"
./plotCostFunction.sh "001_live_background-traffic-1"
./plotCostFunction.sh "001_skype-flow"

