WORKSPACE = ..
LIB_DIR = $(WORKSPACE)/libs
LIB_FILE_NAME = libsimitar.a

all:
	make clean
	make simitar
	make clean-dir

simitar:
	g++ -c *.cpp *.h
	ar rvs $(LIB_FILE_NAME)   *.o
	cp ${LIB_FILE_NAME} ${LIB_DIR}

clean-dir:
	rm -f *.o *.a *.gch
	rm -f ${LIB_FILE_NAME}

clean:
	make clean-dir
	rm -f ${LIB_DIR}/${LIB_FILE_NAME}


