#!/usr/bin/octave-cli -qf
% plotTraceWaveketMra.m
%
% Licensing:
%
%       This code is distributed under the GNU LGPL license.
%
% Modified:
%
%       26 March 2017
%
% Author:
%
%       Anderson Paschoalon
%
% Command line args:
%
%	arg1: experiment name
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Initialization and load data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%inicialization
arg_list = argv ();
close all; clc; clf;
graphics_toolkit ("gnuplot");
set(0, 'DefaultLineLineWidth', 4);
set(0,'defaulttextfontsize', 14);
set(0,'DefaultAxesFontSize',12)
set(0,'DefaultAxesFontName', 'Times New Roman')
EXPERIMENT_NAME = arg_list{1};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Constants
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% plot directory whre the gnuplot data files will be saved
PLOT_DIR = '../../plots/';

% gnuplot data extension
PLOT_DATA_EXT = ".dat";

% path and datafile prefix. file generated by pcap-sniffer.py
DATAFILE_NAME_PREFIX = "../data/packetsinfo_";

%  file extension
DATAFILE_NAME_EXT = ".txt";

% path+file with packet data to be loaded
SIMULATION_DATA = strcat(DATAFILE_NAME_PREFIX, EXPERIMENT_NAME, DATAFILE_NAME_EXT);

% load basic data 
TraceData = dlmread(SIMULATION_DATA, ' ' , 2, 0);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Wavelet multiresolution energy analizis (MREA)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

granularity = 0.01; % 10 ms
vetArrivalTimes = TraceData(:,5);
logEnergy = traceWaveletMra(vetArrivalTimes, granularity);
resolutionLen = length(logEnergy);
res = 1:resolutionLen;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Save data 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
WaveletMREA_Data = [res(:) logEnergy(:)];
title = "WaveletMREA";
labels = "resolution(x), energy_log(y)";
filename = strcat(PLOT_DIR, title, PLOT_DATA_EXT);
matrix2File(WaveletMREA_Data, filename, title, labels);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot data 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%begin
clf;
hold on; grid on;

%settings
set(gca,'Fontname','Timesnewroman');
set(gca, 'fontsize', 20);
ylabel("log2(Energy(j))");
xlabel("Time scale j");
set(gca, 'fontsize', 18);
set(gca, 'LineWidth', 2);

%plotdata
plot1 = plot(res, logEnergy, '-^r');

%legend
legend(EXPERIMENT_NAME, 'Location', 'southoutside', 'Orientation', 'horizontal');

%additional settings
set(plot1, 'LineWidth', 3);

%save plot 
%saveas(gca , '../plots/wavelet-mrea.png');
%save plot 
figure_name = strcat('figures/', EXPERIMENT_NAME, '-', 'WaveletMREA', '.png' );
saveas(gca , figure_name);

%end
hold off; grid off;


