################################################################################
# Configuration file for setting options and parameters for running the
# SIMITAR validations tests, including:
# * Wavelet multiresolution analyzis and Hurst exponent
# * Flows/packets/Mbits per second
# To run evaluation scripts and generate the data, run:
# ./run.py
# To plot or replot the data, run
# ./plot.py
################################################################################


class Config:
    # directory where the pcap files are placed (all pcaps must be in the same directory)
    pcaps_dir = '../Pcaps/'

    # name of the directory where the plots and data will be saved
    plots_dir = 'plots/'

    #  file name of the original pcap file
    pcap_file_1 = 'test.pcap'

    # name of the original pcap file that will be used on the plots
    pcap_name_1 = 'test-pcap'

    # pcap2 file name
    # pcapfile_2 = "pangolin03_skype_simple_tins_host-h2_h1-eth0.client.pcap"
    # pcapfile_2 = "coala_skype_simple_iperf_host-h2_h1-eth0.client.pcap"
    # pcapfile_2 = "wombat03_skype_simple_iperf_host-h1_h1-eth0.client.pcap"
    # pcapfile_2 = "wombat01_skype_simple_tins_h1-eth0.client.pcap"
    # pcapfile_2 = "wombat01_skype_simple_iperf_h1-eth0.client.pcap"
    # pcapfile_2 = "wombat01_skype_tree_iperf_h1-eth0.client.pcap"
    # pcapfile_2 = "ospf.pcap"
    # pcap_file_2 = "guaxinim_lgw10s_simple_tins_host-h1_h1-eth0.client.pcap"
    # pcap_name_2 = "skype-repr-"
    # the prefix of the synthetic pcap files generated by the sumulations. The format of the actual
    # name is pcap_file_2_prefix+i+".pcap". To get the actual pcap file, use Config.pcap_file_2(i).
    pcap_file_2_prefix = 'test'
    pcap_name_2_prefix = 'test'

    # number of synthetic pcap files generated by simulation
    n_runs = 3

    # analyzis name. this name will name the directory where the plots will be saved. Sugestion: fruit name :P
    analysis_name = 'Abacate'

    # pcap1 name that will be used as legend on the plot
    pcap1_type = 'lgw10s-pcap'

    # pcap2 name that will be used as legend on the plot
    pcap2_type = 'simitar-tins'

    # just some information that will be recorded on the file about.log
    # comments = "Neste esperimento executei o simitar utilizando como ferramenta o iperf, em uma topologia arvore SDN.
    # # O cliente (gerador de pacotes) era o host h1, e os clientes os hosts h2-h8."
    comments = 'Neste esperimento executei o simitar utilizando como ferramenta Libtins(C++), em uma topologia single'+\
               ' hop SDN. O cliente (gerador de pacotes) era o host h1, e o servidor os hosts h2-h8. Estou tentando'+\
               ' reproduzir um pesado trafego de um lan gateway por 10 segundos.'

    ############################################################################
    # do not change
    ############################################################################
    # returns the path+name of the original pcap file
    @staticmethod
    def pcap1():
        return Config.pcaps_dir + Config.pcap_file_1

    # returns the path_name of n-th synthetic pcap file
    @staticmethod
    def pcap2(i):
        return Config.pcaps_dir + Config.pcap_file_2_prefix + str(i) + '.pcap'

    # returns the name to be used for the n-th pcap
    @staticmethod
    def pcap_name_2(i):
        return Config.pcap_name_2_prefix + str(i)

    # returns the pcap file name for the n-th pcap
    @staticmethod
    def pcap_file_2(i):
        return Config.pcap_file_2_prefix + str(i) + '.pcap'

    # analysis-pkt-filter.py csv file name
    @staticmethod
    def pktfilter_out_file(pcap_file_name):
        return 'packetsinfo_' + pcap_file_name + '.csv'

