#!/usr/bin/octave-cli -qf
% analysis-hurstExponent.m
%
% Licensing:
%
%       This code is distributed under the GNU LGPL license.
%
% Modified:
%
%       26 March 2017
%
% Author:
%
%       Anderson Paschoalon
%
% Command line args:
%
%	arg1: datafile1, generated by pkt-filter.py
%	arg2: datafile2, generated by pkt-filter.py
%
% Usage:
%
%	./hustExponent.m packetsinfo_wombat.csv packetsinfo_wombat.csv

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Initialization and load data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%inicialization
arg_list = argv ();
close all; clc; clf;
DATA_FILE1 = arg_list{1};
DATA_FILE2 = arg_list{2};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Constants
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% plot directory whre the gnuplot data files will be saved
DATA_DIR = './data/';

% gnuplot data extension
PLOT_DATA_EXT = ".dat";

% path and datafile prefix. file generated by pcap-sniffer.py
DATAFILE_PREFIX = './data/';

%  file extension
DATAFILE_NAME_EXT = ".txt";

% path+file with packet data to be loaded
SIMULATION_DATA1 = strcat(DATAFILE_PREFIX, DATA_FILE1);
SIMULATION_DATA2 = strcat(DATAFILE_PREFIX, DATA_FILE2);

% load basic data 
TraceData1 = dlmread(SIMULATION_DATA1, ',' , 2, 0);
TraceData2 = dlmread(SIMULATION_DATA2, ',' , 2, 0);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Wavelet multiresolution energy analizis (MREA)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
interArrival1 = TraceData1(:, 4);
h1 = hurst(interArrival1);
interArrival2 = TraceData2(:, 4);
h2 = hurst(interArrival2);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Save data 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h = [h1 h2];
title = 'hust exponent : inter-packet times';
labels = strcat('Hurst:',DATA_FILE1 ,', Hurst:',DATA_FILE2);
filename = strcat(DATA_DIR, title, PLOT_DATA_EXT);
matrix2File(h, filename, title, labels);

